# 🚀 Railway PORT (VERY IMPORTANT)
server.port=${PORT:8080}

# ❌ Disable DB (since you commented MySQL)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# 🧠 Optional logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true